---
name: Build and Deploy prometheus-community/helm-charts changelogs to Github Pages

on:
  push:
  schedule:
    - cron: "*/30 * * * *"

env:
  REPOSITORY: prometheus-community/helm-charts
  BRANCH: main
  TYPE: helm
  VERSION: 0.0.1

jobs:
  build_and_deploy:
    name: Build and deploy site
    runs-on: ubuntu-22.04
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout BapRx/changelogs
        uses: actions/checkout@v3
        with:
          path: changelogs

      - name: Checkout ${{ env.REPOSITORY }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPOSITORY }}
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH }}
          fetch-depth: 0

      - name: Check if there are new commits since last Github Action job
        id: check-last-commit-date
        run: |
          # Skip run if no new commit since last Github Action job
          now=$(date +%s)
          lastcommit=$(git log -1 --format=%ct)
          delta=$((now - lastcommit))
          # 1800 -> 30 min
          [[ "$delta" -ge "1800" ]] && echo "updated=false" >> $GITHUB_OUTPUT || exit 0
        shell: bash
        working-directory: ${{ env.REPOSITORY }}

      - name: Generate Changelogs for ${{ env.REPOSITORY }}
        run: |
          # Download release ${VERSION} of helm-changelog
          tmpdir=$(mktemp -d)
          curl -fLsC - -o "$tmpdir/helm-changelog.tar.gz" "https://github.com/mogensen/helm-changelog/releases/download/v${VERSION}/helm-changelog_${VERSION}_linux_amd64.tar.gz"
          tar zxvf "$tmpdir/helm-changelog.tar.gz" -C /usr/local/bin/ helm-changelog

          # Delete pre-existing changelogs
          find . -type f -name Changelog.md -delete

          # Generate new changelogs
          helm-changelog

          # Process and move Changelog.md files to a specific directory
          mkdir -p "${GITHUB_WORKSPACE}/changelogs/_changelogs"
          rm -rf "${GITHUB_WORKSPACE}/changelogs/_changelogs/${TYPE}/"
          find . -type f -name Changelog.md -not -empty | while read line; do
            dn=$(dirname $line)
            fn=$(basename $dn)
            if [ ! -d "${GITHUB_WORKSPACE}/changelogs/_changelogs/${TYPE}/" ]; then
                mkdir "${GITHUB_WORKSPACE}/changelogs/_changelogs/${TYPE}/"
                echo -e "---\nredirect_from:\n  - /\nhas_children: true\n---\n# ${TYPE}\n" >"${GITHUB_WORKSPACE}/changelogs/_changelogs/${TYPE}/index.md"
            fi
            if [ ! -d "${GITHUB_WORKSPACE}/changelogs/_changelogs/${TYPE}/${REPOSITORY//\//_}/" ]; then
                mkdir "${GITHUB_WORKSPACE}/changelogs/_changelogs/${TYPE}/${REPOSITORY//\//_}/"
                echo -e "---\nparent: ${TYPE}\nhas_children: true\n---\n# ${REPOSITORY}\n" >"${GITHUB_WORKSPACE}/changelogs/_changelogs/${TYPE}/${REPOSITORY//\//_}/index.md"
            fi
            sed -i '1i---\nrender_with_liquid: false\nparent: '${REPOSITORY}'\ngrand_parent: '${TYPE}'\n---\n' $line
            sed -i "s/^# Change Log$/# $fn/" $line
            mv $line "${GITHUB_WORKSPACE}/changelogs/_changelogs/${TYPE}/${REPOSITORY//\//_}/$fn.md"
          done
        shell: bash
        working-directory: ${{ env.REPOSITORY }}
        if: ${{ steps.check-last-commit-date.outputs.updated != 'false' }}

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
        if: ${{ steps.check-last-commit-date.outputs.updated != 'false' }}

      - name: Build Jekyll for GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
          jekyll_src: changelogs
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.check-last-commit-date.outputs.updated != 'false' }}
