---
name: Build Helm changelogs

on:
  pull_request:
    branches: [main]

env:
  HELM_CHANGELOG_VERSION: 0.0.2

jobs:
  test:
    name: Build and deploy site
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout BapRx/changelogs
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate Helm Changelogs
        run: |
          # Download release ${HELM_CHANGELOG_VERSION} of helm-changelog
          tmpdir=$(mktemp -d)
          curl -fLsC - -o "$tmpdir/helm-changelog.tar.gz" "https://github.com/BapRx/helm-changelog/releases/download/v${HELM_CHANGELOG_VERSION}/helm-changelog_${HELM_CHANGELOG_VERSION}_linux_amd64.tar.gz"
          tar zxvf "$tmpdir/helm-changelog.tar.gz" -C /usr/local/bin/ helm-changelog

          # Delete pre-existing changelogs
          find . -type f -name Changelog.md -delete

          # Generate new changelogs
          git submodule foreach helm-changelog -v info

          # Process and move Changelog.md files to a specific directory
          find . -type f -name Changelog.md -not -empty | while read line; do
            directory_name=$(dirname $line)
            chart_name=$(basename $directory_name)
            repository=$(echo $directory_name | cut -d/ -f 2-3)
            if [ ! -d "${GITHUB_WORKSPACE}/_changelogs/${repository//\//_}/" ]; then
                mkdir "${GITHUB_WORKSPACE}/_changelogs/${repository//\//_}/"
                echo -e "---\nhas_children: true\nlayout: default\npermalink: /${repository}\ntitle: ${repository}\n---\n\n# ${repository}" >"${GITHUB_WORKSPACE}/_changelogs/${repository//\//_}/index.md"
            fi
            sed -i '1i---\nlayout: default\nparent: '${repository}'\npermalink: /'${repository}'/'${chart_name}'\nrender_with_liquid: false\ntitle: '${chart_name}'\n---\n' $line
            sed -i "s/^# Change Log$/# ${chart_name}/" $line
            mv $line "${GITHUB_WORKSPACE}/_changelogs/${repository//\//_}/${chart_name}.md"
          done
        working-directory: repositories
